### ISSUE TITLE
EPP: Use Dedicated Service Account

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api-inference-extension#224]
Currently, the EPP manifest (`ext_proc.yaml`) creates clusterrolebindings and clusterroles resources to allow the informers to get/list/watch resources. However, roles and rolebindings resources can be used for inferencemodels, inferencepools, and endpointslices. For example:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read
  namespace: default
rules:
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencemodels"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencepools"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-read-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default # We should create a service account for EPP
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-read
```

Additionally, why are the subjectaccessreviews and tokenreviews resources required?

**Comment by kfswain** [comment]
What is the suggested change here? clusterrolebinding is necessary for cross-namespace, which would be necessary for multitenancy, correct?

**Comment by danehans** [comment]
> clusterrolebinding is necessary for cross-namespace, which would be necessary for multitenancy, correct?

Correct but currently the EPP only needs to read namespace-local resources.

**Comment by danehans** [comment]
@kfswain @ahg-g do you know why ^ RBAC rules are required?

**Comment by danehans** [comment]
Metrics are authenticated (via TokenReviews) and authorized (via SubjectAccessReviews) with the kube-apiserver. For the authentication and authorization, EPP needs a ClusterRole with the following rules:
```yaml 
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
```
