### ISSUE TITLE
bug: istio gateway omits headers

### ISSUE THREAD

**Issue by EyalPazz** [kubernetes-sigs/gateway-api-inference-extension#934]
**What happened**:

istio for both vllm-sim and cpu based model's seems to omit the headers for some reason, i get these errors:
`Failed to read and parse request body, unexpected end of JSON input`

`{"object":"error","message":"[{'type': 'missing', 'loc': ('body',), 'msg': 'Field required', 'input': None}]","type":"Bad Request","param":null,"code":400}`

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the [Getting Started Guide](https://gateway-api-inference-extension.sigs.k8s.io/guides) for istio 
**Anything else we need to know?**:
It did work using Kgateway, and also when making the request from inside the pod, so i don't think the problem is in vllm/vllm-sim or in `epp`

**Environment**:
** M4 Pro Chip ** 
- Kubernetes version (use `kubectl version`): v1.33.1
- Inference extension version: v0.3.0
- Cloud provider or hardware configuration: Kind using Cloud Provider Kind for exposing the LB 

cc @nirrozenbaum @danehans

**Comment by nirrozenbaum** [comment]
cc @LiorLieberman @shaneutt

**Comment by shaneutt** [comment]
cc @robscott @aslakknutsen

**Comment by danehans** [comment]
cc: @howardjohn

**Comment by LiorLieberman** [comment]
@nirrozenbaum @shaneutt do you have a list of bugs? I recall issues on different repositories. 
will try to fix them in one goal

**Comment by nirrozenbaum** [comment]
created a thread on GIE slack channel and tagged both of you @LiorLieberman @shaneutt

**Comment by keithmattix** [comment]
Oh I think I ran into this issue! From what I understand, the issue is that t[he DestinationRule to configure SIMPLE TLS](https://raw.githubusercontent.com/kubernetes-sigs/gateway-api-inference-extension/main/config/manifests/gateway/istio/destination-rule.yaml) is hardcoded to a specific service name that doesn't match the EPP that's deployed when using vllm-sim. When I modified the destination rule to use the correct service name, it worked flawlessly:
```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: epp-insecure-tls
  namespace: default
spec:
  host: vllm-llama3-8b-instruct-epp
  trafficPolicy:
    tls:
      insecureSkipVerify: true
      mode: SIMPLE
```
