### ISSUE TITLE
Conformance: Remove Unused Namespace

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api-inference-extension#990]
The following namespace exists in `conformance/resources/manifests/manifests.yaml` and is unused:

```yaml
# Namespace for simple web server backends. This is expected by
# the upstream conformance suite's Setup method.
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-conformance-web-backend
  labels:
    gateway-conformance: web-backend
```

If needed, explore upstream (Gateway API) options for making this namespace optional.
